chore: add MIT license headers to source files and update Makefiles for architecture support

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -2,6 +2,7 @@ SRC_DIR = src
 INC_DIR = include
 OBJ_DIR = $(BUILD_DIR)/obj/kernel
 DRIVERS_OBJ_DIR = $(BUILD_DIR)/obj/drivers
+ARCH_LIB_OBJ_DIR = $(BUILD_DIR)/obj/arch-$(ARCH)
 
 KERNEL_NAME = kafka-kernel-$(ARCH)
 KERNEL_BIN = $(BUILD_DIR)/$(KERNEL_NAME)
@@ -15,6 +16,7 @@ C_OBJS = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/$(ARCH)-%.o,$(C_SRCS))
 OBJS = $(CPP_OBJS) $(C_OBJS)
 
 DRIVER_OBJS = $(shell find $(DRIVERS_OBJ_DIR) -name "$(ARCH)-*.o")
+ARCH_OBJS = $(shell find $(ARCH_LIB_OBJ_DIR) -name "$(ARCH)-*.o")
 
 INCLUDES = -I$(INC_DIR) -I$(PUB_INCLUDE_DIR)
 LDFLAGS = -T $(CURDIR)/../arch/$(ARCH)/linker.ld -nostdlib
@@ -25,12 +27,19 @@ all: $(KERNEL_BIN)
 
 $(KERNEL_BIN): $(OBJS) driver_objs
 	@echo "Linking kernel..."
-	@$(LD) $(LDFLAGS) -o $@ $(OBJS) $(DRIVER_OBJS)
+	@$(LD) $(LDFLAGS) -o $@ $(OBJS) $(ARCH_OBJS) $(DRIVER_OBJS)
 
 driver_objs:
 	@echo "Checking for driver objects..."
 	@if [ ! -d "$(DRIVERS_OBJ_DIR)" ]; then \
 		echo "Driver objects directory not found!"; \
+		exit 1; \
+	fi
+
+arch_objs:
+	@echo "Checking for arch objects..."
+	@if [ ! -d "$(ARCH_LIB_OBJ_DIR)" ]; then \
+		echo "Arch objects directory not found!"; \
 		exit 1; \
 	fi
 
@@ -47,4 +56,4 @@ $(OBJ_DIR)/$(ARCH)-%.o: $(SRC_DIR)/%.c
 clean:
 	@rm -rf $(OBJ_DIR)/$(ARCH)-* $(KERNEL_BIN)
 
-.PHONY: all clean driver_objs
+.PHONY: all clean arch_objs driver_objs
